idf_component_register(
    SRCS
        "main.c"
        "uart_stm.c"
        "wifi.c"
        "ble_prov.c"
        "http.c"
        "mqtt.c"
        "ota.c"
        "swd.c"
    INCLUDE_DIRS
        "."
        "../Inc"
    REQUIRES
        libswd
        nvs_flash
        wifi_provisioning
        esp_http_client
        json
    EMBED_TXTFILES
        "rc_oxi_cert.pem"
)
